database:
  type: "postgresql"
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "your_password"
  name: "company"

encryption:
  public_key_path: "keys/public_key.pem"

storage:
  type: "local"
  path: "backups/"

logging:
  level: "INFO"
  file: "backup.log"